server:
  port: 8082
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

  kafka:
    consumer:
      topic: "demo"
      bootstrap-servers: localhost:9092
      group-id: final-boss-consumer
    producer:
      bootstrap-servers: localhost:9092
      topic: "events"
      group-id: final-boss-producer
